<template>
  <div>
    <b-row v-if="userId">
      <b-col cols="3">
        <LeftPanel />
      </b-col>
      <b-col cols="6">
        <ContentFeed />
      </b-col>
      <b-col cols="3">
        <RightPanel />
      </b-col>
    </b-row>
    <b-row v-else class="pleaseLoginWrapper">
      <div class="pleaseLoginWrapper">
        <div class="img-wrapper slide-top">
          <img width="300" :src="mySVG" />
        </div>
        <h3>Ops</h3>
        <p>Please, login to start your healing journey</p>
         <router-link to="/signup" tag="button" class="btn btn-primary w-100">Go</router-link>
         <!-- <router-link to="/signup" type="button" class="btn outline-primary">Block Level Button</router-link> -->
      </div>
    </b-row>
  </div>
</template>

<script>
import Navbar from "@/components/Navbar";
import ContentFeed from "@/components/ContentFeed";
import LeftPanel from "@/components/LeftPanel";
import RightPanel from "@/components/RightPanel/index.vue";
import { getFromLocal, removeFromLocal } from "@/utils/localStorage";
export default {
  name: "Landing",
  components: {
    Navbar,
    ContentFeed,
    LeftPanel,
    RightPanel,
  },
  data() {
    return {
      mySVG: require("@/assets/undraw_Login_re_4vu2.svg"),
    };
  },
  computed: {
    userId() {
      const userId = this.$store.state.user || getFromLocal("user");
      return userId;
    },
  },
};
</script>

<style scoped>
/* ----------------------------------------------
 * Generated by Animista on 2021-10-14 23:28:31
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-top
 * ----------------------------------------
 */
@-webkit-keyframes slide-top {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
  }
  100% {
    -webkit-transform: translateY(-100px);
    transform: translateY(-100px);
  }
}
@keyframes slide-top {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
  }
  100% {
    -webkit-transform: translateY(-100px);
    transform: translateY(-100px);
  }
}

.slide-top:hover {
  /* -webkit-animation: slide-top 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both; */
  animation: slide-top 0.5s 2 alternate;
  /* transition: all 1.5s;
  -webkit-transition: all 1.5s; */
}
.slide-top {
  /* -webkit-transition: all 1.5s;
  transition: all 1.5s; */
}

.pleaseLoginWrapper {
  height: 70vh;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}
</style>
